version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: alemu2502/my-react-docker-app:latest
    environment:
      - VITE_SERVICE_ID=${VITE_SERVICE_ID}
      - VITE_TEMPLATE_ID=${VITE_TEMPLATE_ID}
      - VITE_USER_ID=${VITE_USER_ID}
      - VITE_GITHUB=${VITE_GITHUB}
      - VITE_FACEBOOK=${VITE_FACEBOOK}
      - VITE_LINKEDIN=${VITE_LINKEDIN}
      - VITE_TWITTER=${VITE_TWITTER}
